### ISSUE TITLE
[EPIC] Crearea portofoliului digital

### ISSUE THREAD

**Issue by cristiancasian** [cristiancasian/Artfolio#2]
Acest EPIC include funcționalități care permit artiștilor să își creeze și să își organizeze portofoliul digital.

### User Stories
- [ ] #2: Organizarea lucrărilor în categorii.
- [ ] #3: Adăugarea descrierilor și tag-urilor.
- [ ] #4: Partajarea portofoliului cu alte persoane.
