### ISSUE TITLE
[EPIC] Colaborare între artiști

### ISSUE THREAD

**Issue by cristiancasian** [cristiancasian/Artfolio#4]
- [ ] *User Story 1:* Ca utilizator, vreau să creez proiecte colaborative.
- [ ] *User Story 2:* Ca utilizator, vreau să invit alți artiști la proiectele mele.
- [ ] *User Story 3:* Ca utilizator, vreau să discut idei creative în spații private.
