### ISSUE TITLE
[EPIC] Feedback și evaluări

### ISSUE THREAD

**Issue by cristiancasian** [cristiancasian/Artfolio#5]
- [ ] *User Story 1:* Ca utilizator, vreau să primesc feedback sub formă de comentarii.
- [ ] *User Story 2:* Ca utilizator, vreau să primesc badge-uri pentru lucrări.
- [ ] *User Story 3:* Ca utilizator, vreau să îmi analizez popularitatea lucrărilor.
